### ISSUE TITLE
It is GSL version 2.4 strictly required?

### ISSUE THREAD

**Issue by jgalan** [sebhoof/SolarAxionFlux#1]
Hi there, at the CMakeLists it is imposed to use GSL 2.4 or higher.

It is the completely necessary? I am working on a system where 2.3 is installed by default. Therefore I just updated the `CMakeLists.txt` to just require 2.3.

```
find_package(GSL 2.3 REQUIRED)
```

It seems everything compiled normally with 2.3. So it could be updated to require GSL 2.3?

**Comment by sebhoof** [comment]
I think the "hard" requirement for the GSL version is >=2.0. As far as I remember, we increased the version because of some significant bug fixes. Looking at the change log, the fixes introduced in 2.3->2.4 specifically do not seem to affect any of the functions we use, so a downgrade of the requirement is fine. I've pushed this change to the master branch ([commit 1445db0df272a32f63f345ea611007256337794d](https://github.com/sebhoof/SolarAxionFlux/commit/1445db0df272a32f63f345ea611007256337794d)).
